[package]
name = "fizzbuzz"
version = "0.1.0"
authors = ["Jorge Ram√≥n <jorge.ramon2128@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
